---
- name: Uninstall k3s server
  hosts: server
  become: true
  tasks:
    - name: delete everything
      ansible.builtin.command:
        argv: 
          - /usr/bin/kubectl
          - delete
          - daemonsets
          - replicasets
          - services
          - deployments
          - pods
          - rc
          - ingress
          - --all 
          - --all-namespaces
    - name: Run K3s Uninstall script server
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
    - name: Get k3s reference
      ansible.builtin.command: which k3s
      register: k3s_path
    - set_fact:
        k3s_path: "{{ k3s_path }}"
    - name: Remove k3s paths
      ansible.builtin.command: rm "{{ k3s_path  }}"
    - name: Remove k3s binaries
      file:
        path: /usr/local/bin/k3s
        state: absent
    -  name: Remove secrets
       file:
         path: /etc/rancher/node
         state:  absent 
- name: Uninstall k3s server
  hosts: agent
  become: true
  tasks:
    - name: Run K3s Uninstall script [agent]
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-agent-uninstall.sh
        removes: /var/lib/rancher/k3s/
    - name: Get k3s reference
      ansible.builtin.command: which k3s
      register: k3s_path
    - set_fact:
        k3s_path: "{{ k3s_path }}"
    - name: Remove k3s paths
      ansible.builtin.command: rm "{{ k3s_path  }}"
    - name: Remove k3s binaries
      file:
        path: /usr/local/bin/k3s
        state: absent
    -  name: Remove secrets
       file:
         path: /etc/rancher/node
         state:  absent
